title: Token Scam Inspector Docs
description: Dev log and specs
theme: null

# GitHub Pages (project site) 用
url: "https://badjoke-lab.github.io"
baseurl: "/token-scam-inspector"

# /dev-log/2025-12-25/ の形式にする
permalink: pretty

# <details markdown="1"> の中をMarkdownとして扱うため
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

# 余計なブログ要素は使わない
plugins: []
