title: Dev Log
description: Development logs and specs
kramdown:
  parse_block_html: true

permalink: pretty

# IMPORTANT:
# - User/Org Pages: baseurl: ""
# - Project Pages: baseurl: "/REPOSITORY-NAME"
baseurl: "token-scam-inspector"

# GitHub Pagesは安全上、プラグインが強く制限されるので使わない方針
# （この構成はプラグイン不要）
exclude:
  - node_modules
  - vendor
  - Gemfile
  - Gemfile.lock
  - README.md
